project:
  type: website

website:
  title: "Joe Collins"
  site-url: https://jcollinsagriculture.co.uk/
  navbar:
    left:
      - href: 00_Home.qmd
        text: Home
      - href: 01_conservation_agriculture.qmd
        text: Conservation Agriculture
      - href: 02_CA_systems_research.qmd
        text: CA Systems Research
      - href: 03_articles.qmd
        text: Articles
      - href: 04_code.qmd
        text: Code
      - href: 05_about.qmd
        text: About
      - href: 06_contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/jwollins
      - icon: twitter
        href: https://x.com/soil_joe
      - icon: linkedin
        href: https://linkedin.com/in/joe-collins-636205123
    include-after-body: "footer.html"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    include-after-body: footer.html
    css: styles.css
    toc: true

resources:
  - CNAME


