project:
  type: website

website:
  title: "Joe Collins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: HAU_BASE_CASE.qmd
        text: Conservation Ag Systems
      - href: articles.qmd
        text: Articles
      - href: code.qmd
        text: Code
      - about.qmd
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/jwollins
      - icon: twitter
        href: https://x.com/soil_joe
      - icon: linkedin
        href: https://linkedin.com/in/joe-collins-636205123
    include-after-body: "footer.html"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    include-after-body: footer.html
    css: styles.css
    toc: true



