project:
  type: website

website:
  title: "Joe Collins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles.qmd
        text: Articles
      - about.qmd
      - href: contact.qmd
        text: Contact
  

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true


