project:
  type: website

website:
  title: "Joe Collins "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: contact.qmd
        text: Contact
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


