[build]
  command = "wget -qO- https://quarto.org/download/latest/quarto-linux-amd64.deb | sudo dpkg -i - && quarto render"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"  # Ensure correct Node.js version
  QUARTO_VERSION = "1.3.450"  # Set the correct Quarto version
